apiVersion: v1
kind: PersistentVolume
metadata:
  name: gcs-fuse-pileval-llama-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 5Gi
  storageClassName: ""
  mountOptions:
    - implicit-dirs
  csi:
    driver: gcsfuse.csi.storage.gke.io
    volumeHandle: infinigram_v4_pileval_llama
    readOnly: false
  claimRef:
    name: gcs-fuse-pileval-llama-pvc
    namespace: default
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gcs-fuse-pileval-llama-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: ""
  volumeName: gcs-fuse-pileval-llama-pv
