# TODO: See if this can be made into a StatefulSet so it can automatically delete the PVC and PV
apiVersion: v1
kind: Pod
metadata:
  name: infini-gram-unigram-checker
spec:
  containers:
  - name: olmoe-mix-0924-nodclm-infini-gram-writer
    image: nginx
    volumeMounts:
    # - mountPath: /mnt/infinigram-array/v4_pileval_llama
    #   name: infinigram-array-pileval-gpt2
    #   readOnly: true
    # - mountPath: /mnt/infinigram-array/dolma_1_7
    #   name: infinigram-array-dolma-1-7-llama
    #   readOnly: true
    - mountPath: /mnt/infinigram-array/olmoe-mix-0924-dclm
      name: infinigram-array-olmoe-mix-0924-dclm
      readOnly: true
    - mountPath: /mnt/infinigram-array/olmoe-mix-0924-nodclm
      name: infinigram-array-olmoe-mix-0924-nodclm
      readOnly: true
    - mountPath: /mnt/infinigram-array/v4-ultrafeedback
      name: infinigram-array-v4-ultrafeedback
      readOnly: true
    - mountPath: /mnt/infinigram-array/v4-tulu-v3-1-mix
      name: infinigram-array-v4-tulu-v3-1-mix
      readOnly: true
    - mountPath: /mnt/infinigram-array/v4-olmo-2-1124-13b-anneal-adapt
      name: infinigram-array-v4-olmo-2-1124-13b-anneal-adapt
      readOnly: true
    - mountPath: /mnt/infinigram-array/pileval-llama
      name: infinigram-array-pileval-llama
      readOnly: true
    env: 
    - name: INDEX_NAME
      value: v4_olmoe-mix-0924-nodclm_llama
  
  volumes:
  # - name: infinigram-array-pileval-gpt2
    # persistentVolumeClaim:
    #   claimName: infinigram-pileval-llama-writer
      # readOnly: true
  - name: infinigram-array-olmoe-mix-0924-dclm
    persistentVolumeClaim:
      claimName: infinigram-olmoe-mix-0924-writer
      readOnly: true
  - name: infinigram-array-olmoe-mix-0924-nodclm
    persistentVolumeClaim:
      claimName: infinigram-olmoe-mix-0924-nodclm-writer
      readOnly: true
  - name: infinigram-array-v4-ultrafeedback
    persistentVolumeClaim:
      claimName: infinigram-v4-ultrafeedback-writer
      readOnly: true
  - name: infinigram-array-v4-tulu-v3-1-mix
    persistentVolumeClaim:
      claimName: infinigram-v4-tulu-v3-1-mix-writer
      readOnly: true
  - name: infinigram-array-v4-olmo-2-1124-13b-anneal-adapt
    persistentVolumeClaim:
      claimName: infinigram-v4-olmo-2-1124-13b-anneal-adapt-writer
      readOnly: true
  - name: infinigram-array-pileval-llama
    persistentVolumeClaim:
        claimName: infinigram-pileval-llama-writer
        readOnly: true
  # - name: infinigram-array-dolma-1-7-llama
  #   persistentVolumeClaim:
  #     claimName: infinigram-dolma-1.7-llama
  #     readOnly: true
  restartPolicy: Never
