apiVersion: v1
kind: Service
metadata:
  name: otelcol
spec:
  selector:
    app: otel-collector
  ports:
  - port: 4318
    targetPort: 4318
    name: otlp-http
  - port: 4317
    targetPort: 4317
    name: otlp-grpc
  - port: 8888
    targetPort: 8888
    name: metrics 