apiVersion: apps/v1
kind: Deployment
metadata:
  name: infinigram-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: infinigram-proxy
  template:
    metadata:
      labels:
        app: infinigram-proxy
    spec:
      containers:
        - name: proxy
          image: gcr.io/consus-394000/ashish/infini-gram-proxy:latest
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: proxy-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
      volumes:
        - name: proxy-config
          configMap:
            name: proxy-conf
