apiVersion: apps/v1
kind: Deployment
metadata:
  name: infinigram-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: infinigram-api
  template:
    metadata:
      labels:
        app: infinigram-api
    spec:
      initContainers:
      - name: create-index-dirs
        image: busybox
        command: ['sh', '-c', 'mkdir -p /mnt/infinigram-array/v4_pileval_llama /mnt/infinigram-array/olmoe-mix-0924-dclm /mnt/infinigram-array/olmoe-mix-0924-nodclm /mnt/infinigram-array/v4-olmoe-0125-1b-7b-anneal-adapt /mnt/infinigram-array/v4-olmo-2-1124-13b-anneal-adapt /mnt/infinigram-array/v4-olmo-2-0325-32b-anneal-adapt /mnt/infinigram-array/v4-tulu-3-8b-adapt-llama /mnt/infinigram-array/v4-tulu-3-70b-adapt-llama /mnt/infinigram-array/v4-tulu-3-405b-adapt-llama /mnt/infinigram-array/v4-tulu-3-8b-adapt /mnt/infinigram-array/v4-tulu-3-70b-adapt /mnt/infinigram-array/v4-tulu-3-405b-adapt']
        volumeMounts:
        - name: infinigram-array
          mountPath: /mnt/infinigram-array
      containers:
        - name: api
          image: gcr.io/consus-394000/ashish/infini-gram-api:latest
          ports:
            - containerPort: 7860
          envFrom:
            - configMapRef:
                name: infinigram-env
          readinessProbe:
            httpGet:
              path: /health
              port: 7860
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          volumeMounts:
            - mountPath: /mnt/infinigram-array
              name: infinigram-array
            - mountPath: /mnt/infinigram-array/v4_pileval_llama
              name: infinigram-array
            - mountPath: /mnt/infinigram-array/olmoe-mix-0924-dclm
              name: infinigram-array
        - name: attribution-worker
          image: gcr.io/consus-394000/ashish/infini-gram-worker:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: infinigram-env
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          volumeMounts:
            - mountPath: /mnt/infinigram-array
              name: infinigram-array
            - mountPath: /mnt/infinigram-array/v4_pileval_llama
              name: infinigram-array
            - mountPath: /mnt/infinigram-array/olmoe-mix-0924-dclm
              name: infinigram-array
      volumes:
        - name: infinigram-array
          emptyDir: {}
