apiVersion: apps/v1
kind: Deployment
metadata:
  name: infinigram-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: infinigram-api
  template:
    metadata:
      labels:
        app: infinigram-api
    spec:
      containers:
        - name: api
          image: gcr.io/consus-394000/ashish/infini-gram-api:latest
          ports:
            - containerPort: 7860
          envFrom:
            - configMapRef:
                name: infinigram-env
          volumeMounts:
            - mountPath: /mnt/infinigram-array
              name: infinigram-array
        - name: attribution-worker
          image: gcr.io/consus-394000/ashish/infini-gram-worker:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: infinigram-env
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          volumeMounts:
            - mountPath: /mnt/infinigram-array
              name: infinigram-array
      volumes:
        - name: infinigram-array
          persistentVolumeClaim:
            claimName: infinigram-array-pvc
